apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-nodeport
  labels:
    app: vaultwarden-nodeport
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: vaultwarden
